DROP TABLE IF EXISTS visitors;

CREATE TABLE IF NOT EXISTS pre_orders (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(200) NOT NULL,
  whatsapp VARCHAR(50) NOT NULL,
  package VARCHAR(50) NOT NULL,
  vehicle_count INTEGER NOT NULL,
  vehicle_types JSONB NOT NULL,
  start_type VARCHAR(50) NOT NULL,
  start_date VARCHAR(50),
  source VARCHAR(100) DEFAULT 'KAI_SUMMIT_2026',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
